### PR TITLE
add keep/drop

### PR DESCRIPTION
**Pull request by trescenzi**
Didn't get as much time as I'd like but here's the start of the implementation. Few things to note:

~~**This doesn't actually drop any dice in `test` yet.** Wanted to get the parsing + most easily testable methods done first and it's too late for me to do the math for this lol. I'll hopefully have time tomorrow or Sunday to finish this up.~~

I set it up such that `Dice` can understand what it means to `drop` any number of dice from its roll. This means `keep` is translated into `drop` before being given to `Dice`.

Not sure how it makes sense to think about `count` with `keep`/`drop`. Private to `Dice` I added a `count_after_drop`, maybe I should just make this public. What do you think?

### CODE REVIEW

**Review by Nephos — COMMENTED** [review]
That looks nice. I will do some testing to make sure everything before.

**Comment by trescenzi** [comment]
The piece that's still missing is the average calculation. I'm not 100% on the best way to generalize that as an equation. It's stats that's over my head honestly. Never been great at that sort of thing.

I'm looking at brute forcing it though. `each_permutations` is a pretty great helper method. Although it probably gets really slow rather quick. Will do more investigating. I can probably find another open source implementation to copy.

**Comment by trescenzi** [comment]
Found the time to get the brute force average calculation working. Not sure about `average_details` for this as I don't know what it would return. I'd like to add a few more average tests but it worked for some easy to find averages like advantage, disadvantage and 2d6kh1.

**Comment by Nephos** [comment]
For the `dl`, I found

`E(S) = N(d+1)/2 - (1N + 2N + 3N + ... + dN)/dN` [source](https://www.reddit.com/r/askscience/comments/9kl4qj/how_do_you_calculate_the_average_sum_of_dice/)
I think you can also apply this method to `dh` by using the right M probabilities

For kl and kh there is something [there too](https://www.reddit.com/r/statistics/comments/6x1fqw/average_die_roll_keep_the_highestlowest/)

Same as you, it's been a few years last time I had to do big probabilities like these, I'm not used to it.

**Comment by trescenzi** [comment]
Apologies, was busy yesterday with Easter, forgot about that.

I can try those formulas. I don't know if they generalize though beyond just drop lowest 1. Like what about `5d6dl2`? It's likely I'm missing something though since I'm so far removed from my college statistics classes. Maybe even if they don't it makes sense to implement them since they will be significantly faster and weird situations like `5d6l2` can fallback to a slower solution. There's also absolutely better ways to implement what I did. I know it can be done in a single loop at the very least.

Just a heads up my monday + tuesdays are usually busy but I'll get a chance to circle back on wednesday evening.

Please feel free to change whatever as well(not tied to any implementation) especially if you find issues while testing 😄

**Comment by Nephos** [comment]
I'll try to merge this noon ! Unless you have something else you want to add.

**Comment by trescenzi** [comment]
Sorry for ghosting, been real busy at work.

It all works in my testing. Only thing I've still been playing around with is `average`. There's room for speed improvements there but haven't had time to get to it. I think it's fine to merge though.

Thanks for accepting it 😃

**Comment by Nephos** [comment]
Yes the same ! It is probably not worth to take a 72 hour courses to improve the performances of this given that most of the time the rolls are limited to a few dice.

**Comment by Nephos** [comment]
I fix some minor errors I found in the format:
trainling space, missing spaces, doubled space, mixed tab/spaces (using `crystal tool format`)

**Comment by Nephos** [comment]
~~I think we are missing the Roll compatibility (the part which allow several dice to be thrown together~~
My bad

**Comment by Nephos** [comment]
You may want to be credited in the authors (shards.yml) or the README ? If you want don't hesitate to add your name. I've verified everything I wanted so I'm ready to press Enter to merge the patch

**Comment by trescenzi** [comment]
I'm fine with whatever. I guess leave me out for now, although I'm always happy to help out more if other stuff comes up and I have time.

Excited to see it merged. Thanks again!

**Comment by Nephos** [comment]
<3

**Pull request merged**
